### ISSUE TITLE
virtualenv in prompt

### ISSUE THREAD

**Issue by ywpkwon** [Parth/dotfiles#35]
Thanks for this great work!

I found one drawback that the promt does not work with python `virtualenv`.
E.g., 
```
$ workon tf
(tf) $            # (tf) is missing
```
How can I use `virtualenv`?

In addition, if I want to use standard `ZSH_THEME="agnoster"`, could you advise how/where I can  modify?

**Comment by Parth** [comment]
Did you ever find a solution to this issue? I'll check it out at some point if not.

So I'd take a look at [this file](https://github.com/Parth/dotfiles/blob/master/zsh/zshrc.sh), this is what modifies zsh's behavior. If you wanted to add something, that would be a good starting point. 

BUT, one of the things I did was changed the [prompt](https://github.com/Parth/dotfiles/blob/master/zsh/prompt.sh)'s behavior. And that's something `agnoster` does as well if I recall correctly. So I'd pay careful attention to that interaction as you experiment.

I see this issue is a bit old, what did you end up doing?
